name: Github Action

on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - run: npm install
      - run: npm test
      - run: npm run coverage
      - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: XFlVbkcc2w1pq0qezq04d6nKJaeTNfLon
